// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNScQEBTROmmE-T3JDrx99RJjnR5N2l8A',
    appId: '1:666809986491:web:3ba402cdb18bcb25ad689e',
    messagingSenderId: '666809986491',
    projectId: 'dni-ecommerce',
    authDomain: 'dni-ecommerce.firebaseapp.com',
    storageBucket: 'dni-ecommerce.firebasestorage.app',
    measurementId: 'G-5VJQYXJYHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_OCour8lf-9e9oskAPaBAovdpypfaZBY',
    appId: '1:666809986491:android:94d593650a8f101bad689e',
    messagingSenderId: '666809986491',
    projectId: 'dni-ecommerce',
    storageBucket: 'dni-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAfpnFyl2C7GoK_1CqDdb_HTeL2I_N_qc',
    appId: '1:666809986491:ios:8a50df16d4905073ad689e',
    messagingSenderId: '666809986491',
    projectId: 'dni-ecommerce',
    storageBucket: 'dni-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.dniEcommerceV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAfpnFyl2C7GoK_1CqDdb_HTeL2I_N_qc',
    appId: '1:666809986491:ios:8a50df16d4905073ad689e',
    messagingSenderId: '666809986491',
    projectId: 'dni-ecommerce',
    storageBucket: 'dni-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.dniEcommerceV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNScQEBTROmmE-T3JDrx99RJjnR5N2l8A',
    appId: '1:666809986491:web:2ba0a428281ba370ad689e',
    messagingSenderId: '666809986491',
    projectId: 'dni-ecommerce',
    authDomain: 'dni-ecommerce.firebaseapp.com',
    storageBucket: 'dni-ecommerce.firebasestorage.app',
    measurementId: 'G-6DHVJ9B47Y',
  );
}
